### ISSUE TITLE
the email is not delivered

### ISSUE THREAD

**Issue by jsamaniegog** [tomolimo/arsurveys#3]
I'm trying to send the notification but does not reach. Following the instructions i've configured "Can be notified" and "Users" to yes in the group and have assigned "Manager of the group in charge of the ticket" to recipients in the notification. What am I doing wrong?

And, the notification is sended when the user click the save button of the satisfaction survey?

Thank you!

**Comment by tomolimo** [comment]
Hello,
What is the group name you have defined?
Regards,
Tomolimo

**Comment by jsamaniegog** [comment]
The name of the group is "telecomunicaciones.clvaeste"

**Comment by tomolimo** [comment]
then you need to add in the recipients for the notification the following recipient:

"manager of the group telecomunicaciones.clvaeste"

and not the "manager of the group in charge of the ticket" as this one will trigger a notification to the manager of all groups when groups are assigned to a ticket. This means that a group MUST be assigned to a ticket.

But in our case, when using "manager of the group XXXX", then the group XXXX doesn't need to be assigned to ticket for the manager to be notified.

is it clearer ?

regards,
Tomolimo

**Comment by jsamaniegog** [comment]
It's clearer. The group is assigned to the ticket and I'm the manager, so it should work...

**Comment by tomolimo** [comment]
Could you do screen copies of the ticket, the notification and group?
Could you also check the log files to see if any error can be found related to ARSurveys?
Could you also give me your GLPi configuration (version,...)?
thank you

**Comment by jsamaniegog** [comment]
The group had two managers and mail had arrived to the other manager but not to me...

The solution was in pesonalization settings, setting "Notifications for my changes" to yes for the testing.

Thank you for your help!
Regards.

**Comment by tomolimo** [comment]
You're welcome
