### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Octogorum** [tomolimo/arsurveys#6]
Hi.
I hope you can help me.
I've installed ARSURVEYS plugin in directory ,but GLPI doesn't show Arsurveys plugin , I mean I cant see the options : (Install , Activate ) in Plugins tab.
I don't know if I've unzipped wrong in directory, other plugins run correctly except ARSURVEY.
Can you tell me how is the correct mode to install it?
I'm using glpi v 0.90.1
Thanks in advance.

**Comment by tomolimo** [comment]
what folder name did you use?

**Comment by Octogorum** [comment]
I used this (Release 1.4.0 -> Source code (tar.gz))

**Comment by tomolimo** [comment]
And what folder name you used in your plugin folder?

**Comment by Octogorum** [comment]
http://postimg.org/image/j3msgu6kh/
This link is an image of plugins folder.

**Comment by tomolimo** [comment]
Rename the folder arsurveys

**Comment by Octogorum** [comment]
It works ! 
Thanks so much ! :v:

**Comment by tomolimo** [comment]
You're welcome
