### ISSUE TITLE
Ticket - Survey

### ISSUE THREAD

**Issue by NIKO-1993** [tomolimo/arsurveys#7]
Hi !
The survey does not appear when the request is resolved.
what should I do for the survey work properly?
thanks in advance.

**Comment by tomolimo** [comment]
Hello,
Is this regarding plugin ARSurveys or GLPi surveys?
Anyway, surveys appear only when ticket is closed by approval of the solution by the requester, and not when solving tickets.
As ti seems that this is a question about GLPi and not ARSurveys plugin: I close the topic, but feel free to re-open it if this really concern this plugin.
Tomolimo
