### ISSUE TITLE
User ARsuveys 

### ISSUE THREAD

**Issue by Ney-123** [tomolimo/arsurveys#8]
hello Tomolimo.
I'm usuando the plugins awsurveys-1.4.0 . I have  problems when configuring.
how I can configure. I want the staff survey, be display to applicant in the moment to close the petition. Already try to do it, But it does not prove to me . I appreciate your support, Thank you.

**Comment by tomolimo** [comment]
Hello,
Could you please described in details what you want to achieve and if necessary post screen copies?
Thank you, 
Regards,
Tomolimo

**Comment by NIKO-1993** [comment]
When a ticket is closed, survey doesn't appear for the requester. I suppose I have to do some configuration in glpi but I don't know what configuration I have to do.
Can you help please?
thanks in advance.

**Comment by tomolimo** [comment]
Sorry, but this is not the right area to post about GLPi features/Questions.
Could you post in the forum?
http://forum.glpi-project.org/
